
services:
  fastapi:
    environment:
      - DOMAIN=${DOMAIN}
      - UVICORN_LOG_LEVEL=debug
      - EQUUS_DATA_DIR=/app/data # Set the path to the data directory within the mounted volume
    build: .
    restart: unless-stopped
    expose:
      - 8000
    networks:
      - equus-web
    volumes:
      - ./equus-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.fastapi.entrypoints=websecure"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"

networks:
  equus-web:
    external: true

volumes:
  equus-data:
