[project]
name = "equus-express"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cryptography>=45.0.5",
    "fastapi>=0.116.0",
    "uvicorn>=0.35.0",
    "jinja2",
    "httpx", # Used by client and test client
]

[tool.setuptools.packages.find]
where = ["src"] # Specify that packages are found under the 'src' directory

[dependency-groups]
dev = [
    "coverage>=7.9.2",
    "pytest-cov>=6.2.1",
]
